# Generated by Django 4.1.3 on 2022-11-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyAPI', '0003_alter_product_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.BinaryField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('file', models.CharField(max_length=11)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyAPI.business')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contact', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_text', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyAPI.business')),
            ],
        ),
    ]
