# Generated by Django 4.1.3 on 2022-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('review_text', models.TextField()),
                ('date_review', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
